### ISSUE TITLE
PGTransactionDelegate method not calling 

### ISSUE THREAD

**Issue by Yesuvin** [Avtar1351992/iOS-examples#2]
Hi 
When i do payment in paytm using your code, PGTransactionDelegate (didSucceedTransaction, didFailTransaction) methods not calling but response printing in console along with HTML tags without calling delegate methods how it is possible?
Thank you

**Comment by AvtMob** [comment]
Hi

Please download the latest object c sdk files from paytm support and then
integrate into my code after that try again for payment test.
Thanks
