### ISSUE TITLE
client ssl certificate

### ISSUE THREAD

**Issue by amitkumar3968** [Avtar1351992/iOS-examples#3]
Hi Avatar,
Can you detail the process of getting ssl certificate via paytm.
I am not seeing any option of this on paytm business site after login.
able to genertate sandbox credentials, but no ssl certificate option coming.
Thanks
Amit.

**Comment by AvtMob** [comment]
Hi Amit thank you so much for connecting, please call to paytm support for
your queries because I have also sort out some problems after call to paytm.
Thanks

**Comment by amitkumar3968** [comment]
ok, thanks very much.
